updates

diff --git a/source/functions b/source/functions
--- a/source/functions
+++ b/source/functions
@@ -1,28 +1,5 @@
 #!/usr/bin/env bash
 
-edit_file() {
-  previous_file="$1"
-  file_to_edit=`select_file $previous_file`
-
-  if [ -n "$file_to_edit" ] ; then
-    "$EDITOR" "$file_to_edit"
-    edit_file "$file_to_edit"
-  fi
-}
-
-cat() {
-   if hash bat 2>/dev/null; then
-        bat -pp "$@"
-   else
-        command cat "$@"
-   fi
-}
-
-select_file() {
-  given_file="$1"
-  fzf --preview="cat {}" --preview-window=right:70%:wrap --query="$given_file"
-}
-
 ID_COLOUR="\033[36m"
 TEXT_COLOUR="\033[34m"
 STATUS_COLOUR="\033[33m"
@@ -52,31 +29,6 @@ my_issues() {
   #xargs -n1 gh issue view -R "$repo" -c
 }
 
-# A SysOps guy once taught me the Three-Fingered Claw technique
-# These functions are *NIX OS and shell flavor-robust. Put them at the beginning of your script (bash or otherwise), try() your statement and code on.
-# Explanation
-
-# yell: print the script name and all arguments to stderr:
-# $0 is the path to the script ;
-# $* are all arguments.
-# >&2 means > redirect stdout to & pipe 2. pipe 1 would be stdout itself.
-yell() {
-  echo "$0: $*" >&2;
-}
-
-# die does the same as yell, but exits with a non-0 exit status, which means “fail”.
-die() {
-  yell "$*"; return 111;
-}
-
-# try uses the || (boolean OR), which only evaluates the right side if the left one failed.
-# $@ is all arguments again, [but different](https://stackoverflow.com/a/3008734/5770188).
-try() {
-  "$@" || die "cannot $*";
-}
-
-echoerr() { printf "\e[31;1m%s\e[0m\n" "$*" >&2; }
-
 make_branch() {
   local issue=$(my_issues)
   local exit_code="$?"
@@ -97,6 +49,7 @@ gch() {
  git checkout "$(git branch --all | fzf | tr -d '[:space:]')"
 }
 
+# make a note in the notes directory
 nn() {
   local note_name="$*"
   local note_date="`date +%F`"
@@ -110,22 +63,52 @@ nn() {
   v "$ATLAS_NOTES_DIR/$note_name"
 }
 
+# search note contents for a term
 ns() {
-  local file
-  [ -z "$1" ] && echo "No argument supplied - Enter a term to search" && return 1
-  file="$(rg --files-with-matches --no-ignore --ignore-case --hidden --no-heading --no-messages $1 $ATLAS_NOTES_DIR | fzf --preview "head -100 {}")"
-  if [[ -n $file ]]
-  then
-    v $file
+  local DIR="$ATLAS_NOTES_DIR"
+  local RG_PREFIX="rg --column --line-number --no-heading --color=always --smart-case -tmd "
+  local INITIAL_QUERY="${*:-}"
+  : | fzf --ansi --disabled --query "$INITIAL_QUERY" \
+    --bind "start:reload:$RG_PREFIX {q} '$DIR'" \
+    --bind "change:reload:sleep 0.1; $RG_PREFIX {q} '$DIR' || true" \
+    --delimiter : \
+    --preview 'bat --color=always {1} --highlight-line {2}' \
+    --preview-window 'right,60%,border-bottom,+{2}+3/3,~3' \
+    --bind 'enter:become(nvim {1} +{2})'
+}
+
+
+# search note filenames
+nl() {
+  local files
+  files="$(rg --files $ATLAS_NOTES_DIR | fzf --delimiter / --with-nth -1 --preview "head -100 {} ")"
+  if [[ -n $files ]]; then
+    v $files
   fi
 }
 
-nl() {
-  local files
-  files="$(rg --files $ATLAS_NOTES_DIR | fzf --preview "head -100 {}")"
+
+alias rgf='rg --files | rg'
+
+# search repos
+rs() {
+  local files="$(rg --files ~/repos | fzf --delimiter / --with-nth -1 --preview 'bat --color=always {}')"
   if [[ -n $files ]]; then
-v $files
+    v $files
   fi
+
+}
+
+cs() {
+  local DIR="~/repos"
+  local RG_PREFIX="rg --files $DIR | rg --column --line-number --no-heading --color=always --smart-case -g '!*test.*' -g '!static/test/*' "
+  local INITIAL_QUERY="${*:-}"
+  : | fzf --ansi --disabled --query "$INITIAL_QUERY" \
+    --bind "start:reload:$RG_PREFIX {q} $DIR" \
+    --bind "change:reload:sleep 0.1; $RG_PREFIX {q} $DIR || true" \
+    --delimiter : \
+    --preview 'bat --color=always {1} --highlight-line {2}' \
+    --bind 'enter:become(code {1} +{2})'
 }
 
 # Create a new directory and enter it
@@ -416,17 +399,17 @@ is_inside_git_repo() {
 }
 
 # clone a repo if it doesn't exist
+# @example
 # repo some-repo-name
 repo() {
-  # if [ ! -d "$HUBSPOT_CODE_DIR/$1" ]; then
-  #   echo "⚠️ Repo missing: \"$1\", cloning into $HUBSPOT_CODE_DIR/$1"
-  #   cd $HUBSPOT_CODE_DIR
-  #   git clone "git@git.hubteam.com:HubSpot/$1.git" || git clone "git@git.hubteam.com:HubSpotProtected/$1.git" || echo "🚨 uh oh, something went wrong cloning $1" && exit $EXITCODE
-  # fi
-  # if [ -d "$HUBSPOT_CODE_DIR/$1" ]; then
-  #   cd $HUBSPOT_CODE_DIR/$1
-  # fi
-  ~/.config/atlas/scripts/repo.ts "$1"
+  if [ ! -d "$HUBSPOT_CODE_DIR/$1" ]; then
+    echo "⚠️ Repo missing: \"$1\", cloning into $HUBSPOT_CODE_DIR/$1"
+    cd $HUBSPOT_CODE_DIR
+    git clone "git@git.hubteam.com:HubSpot/$1.git" || git clone "git@git.hubteam.com:HubSpotProtected/$1.git" || echo "🚨 uh oh, something went wrong cloning $1" && exit $EXITCODE
+  fi
+  if [ -d "$HUBSPOT_CODE_DIR/$1" ]; then
+    cd $HUBSPOT_CODE_DIR/$1
+  fi
 }
 
 # add completion for repos in $HUBSPOT_CODE_DIR
@@ -472,5 +455,5 @@ pretty() {
 
 # run hs projects with my preferred settings
 flexo() {
-  NODE_OPTIONS="--max_old_space_size=8192" bend reactor serve "$@" --update --ts-watch
+  cd "$HUBSPOT_CODE_DIR" && NODE_OPTIONS="--max_old_space_size=8192" bend reactor serve "$@" --update --ts-watch
 }
