various updates

diff --git a/source/functions b/source/functions
--- a/source/functions
+++ b/source/functions
@@ -7,50 +7,6 @@ SHELL_COLOUR="\033[0m"
 # Set to the directory you typically clone your git repos
 CODE_DIR="$HOME/src"
 
-
-my_issues() {
-  local repo="${1:-HubSpot/Billing-Management-Team}"
-  # gh issue list --label 'FE' --assignee '@me' --repo HubSpot/Merchant-Experience-Team
-  local issue_list=$(GH_FORCE_TTY=true gh issue list --label 'FE' --repo "$repo" --assignee '@me')
-
-  if [[ -z $issue_list ]]; then
-    return 1
-  fi
-
-  if [[ ${issue_list} == no* ]]; then
-    return 1
-  fi
-
-  local issue="$(echo "$issue_list" | awk -F'\t' -v ID_COLOUR="$ID_COLOUR" -v TEXT_COLOUR="$TEXT_COLOUR" -v STATUS_COLOUR="$STATUS_COLOUR" -v SHELL_COLOUR="$SHELL_COLOUR" \
-    '{print ID_COLOUR $1 SHELL_COLOUR"\t"TEXT_COLOUR $3 SHELL_COLOUR"\t"STATUS_COLOUR $2}' |
-    fzf -d' ' \
-      --ansi \
-      --prompt="my issues in $repo:")"
-
-  echo "$issue" | cut -f-2
-  #xargs -n1 gh issue view -R "$repo" -c
-}
-
-make_branch() {
-  local issue=$(my_issues)
-  local exit_code="$?"
-  if [[ $exit_code -gt 0 ]]; then
-    echoerr "No issues found"
-    return 1
-  fi
-
-  if [[ -z $issue ]]; then
-    echoerr "No issue selected"
-    return 1
-  fi
-  echo "would have made branch for $issue"
-  # gitb "$issue"
-}
-
-gch() {
- git checkout "$(git branch --all | fzf | tr -d '[:space:]')"
-}
-
 # make a note in the notes directory
 nn() {
   local note_name="$*"
@@ -94,7 +50,7 @@ alias rgf='rg --files | rg'
 
 # search repos
 rs() {
-  local files="$(rg --files ~/repos | fzf --delimiter / --with-nth -1 --preview 'bat --color=always {}')"
+  local files="$(rg --files "$CODE_DIR" | fzf --delimiter / --with-nth -1 --preview 'bat --color=always {}')"
   if [[ -n $files ]]; then
     v $files
   fi
@@ -102,7 +58,7 @@ rs() {
 }
 
 cs() {
-  local DIR="~/repos"
+  local DIR="$CODE_DIR"
   local RG_PREFIX="rg --files $DIR | rg --column --line-number --no-heading --color=always --smart-case -g '!*test.*' -g '!static/test/*' "
   local INITIAL_QUERY="${*:-}"
   : | fzf --ansi --disabled --query "$INITIAL_QUERY" \
@@ -132,7 +88,7 @@ fs() {
   fi;
 }
 
-# Create a data URL from a file
+# Create a data URL from a file (urlencoded string)
 dataurl() {
   local mimeType=$(file -b --mime-type "$1");
   if [[ $mimeType == text/* ]]; then
@@ -141,8 +97,8 @@ dataurl() {
   echo "data:${mimeType};base64,$(openssl base64 -in "$1" | tr -d '\n')";
 }
 
-# `v` with no arguments opens the current directory in Neovim, otherwise opens the
-# given location
+# `v` with no arguments opens the current directory in $EDITOR (neovim)
+# otherwise opens the given location
 v() {
   if [ $# -eq 0 ]; then
     $EDITOR;
@@ -195,14 +151,11 @@ banner() {
   figlet -f banner "$1" | sed -e "s/#/:${2}:/g" | sed -e 's/ /:blank:/g' | pbcopy
 }
 
-##########
-# TMUX
-##########
-
 unbool() {
   tmux kill-server
 }
 
+# Launch or reconnect main tmux session
 bool() {
   local SESSION_NAME="Bool"
   tmux has-session -t $SESSION_NAME 2>/dev/null
@@ -241,16 +194,13 @@ bool() {
   tmux a -t "$SESSION_NAME"
 }
 
-##########
-# FFMPEG
-##########
-
 convert_aiffs() {
   for i in *.aiff;
     do convert_aiff $i;
   done
 }
 
+# Convert .aiff files to .ogg
 convert_aiff() {
   ffmpeg -hide_banner -loglevel error -y -i "$1" -c:a libvorbis -q:a 4 "_$1.ogg";
 }
@@ -261,6 +211,7 @@ convert_gifs() {
   done
 }
 
+# Convert .gif files to .mp4
 convert_gif() {
   ffmpeg -hide_banner -loglevel error -y -f gif -i "$1" -movflags faststart -pix_fmt yuv420p -vf "scale=trunc(iw/2)*2:trunc(ih/2)*2" "_${1.*}.mp4";
 }
@@ -271,6 +222,7 @@ convert_webms() {
   done
 }
 
+# Convert .webm video to .mp4
 convert_webm() {
   echo "Converting $1"
   # ffmpeg -fflags +genpts -i "$1" -r 24 "scale=trunc(iw/2)*2:trunc(ih/2)*2" "_${1.*}.mp4"
@@ -278,10 +230,7 @@ convert_webm() {
 }
 
 
-##########
-# Utilities
-##########
-
+# print a shell color test to determine the level of color support
 colortest() {
   awk 'BEGIN{
     s="/\\/\\/\\/\\/\\"; s=s s s s s s s s s s s s s s s s s s s s s s s;
@@ -317,70 +266,6 @@ confirm() {
   esac
 }
 
-##########
-# Git
-##########
-
-# get default branch name (branch you should branch from for new work)
-gdefault() {
-  command git branch -rl '*/HEAD' | rev | cut -d/ -f1 | rev
-}
-
-# publish local branch
-gpub() {
-  command git push --set-upstream origin $(git_current_branch)
-}
-
-gcr() {
-  command git checkout -t origin/"${@}"
-}
-
-# Clean up local branches that have been merged
-function gclean() {
-  branch=$1
-  if [[ -z "$branch" ]]; then
-    branch=$(gdefault)
-  fi
-  confirm "Are you on a clean branch?" &&
-  command git checkout "$branch" &&
-  command git branch -d $(command git branch --merged="$branch" | grep -v "$branch") &&
-  command git fetch --prune
-}
-
-# Create a new branch and switch to it
-gitb() {
-  # [          # start of character class
-  # [:space:]  # The POSIX character class for whitespace characters. It's
-               # functionally identical to [ \t\r\n\v\f] which matches a space,
-               # tab, carriage return, newline, vertical tab, or form feed. See
-               # https://en.wikipedia.org/wiki/Regular_expression#POSIX_character_classes
-  # ]          # end of character class
-  # \+         # one or more of the previous item (anything matched in the brackets).
-  local branchname=$(echo $1 | sed 's/-//g' | sed -re 's/[[:blank:]]/-/g')
-   if [[ $branchname = no-issue-found* ]]; then
-    echo "No issues found."
-    return 1
-  fi
-  local datestr=$(date +%F)
-  branchname=$(echo "$USER"/"$datestr"/"$branchname")
-  git checkout -b $branchname
-}
-
-
-# Create a new tag and push it to origin
-tag() {
-  command git checkout master
-  command git pull origin master
-  command git fetch --tags
-  command git tag -a "$1" -m "Release $1"
-  command git push origin "$1" --tag
-}
-
-# print a random icebreaker question
-icebreaker() {
-  node "$ATLAS_ROOT/scripts/icebreaker.js"
-}
-
 # open the neovim log file
 nvim_logs() {
   nvim ~/.cache/nvim
@@ -389,61 +274,6 @@ nvim_logs() {
 ####################################################
 # HUBSPOT
 ####################################################
-
-# add completion for repos in $CODE_DIR
-# https://zsh.sourceforge.io/Doc/Release/Completion-Using-compctl.html
-# compctl -M 'm:{a-z}={A-Z}' -K _repo_comp repo
-
-# Completion for repo
-# _repo_comp() {
-#   reply=(`ls $CODE_DIR`);
-# }
-
-is_inside_git_repo() {
-    git rev-parse --is-inside-work-tree >/dev/null 2>&1
-}
-
-# clone a repo if it doesn't exist
-# @example
-# repo some-repo-name
-repo() {
-  if [ ! -d "$CODE_DIR/$1" ]; then
-    echo "⚠️ Repo missing: \"$1\", cloning into $CODE_DIR/$1"
-    cd $CODE_DIR
-    git clone "git@git.hubteam.com:HubSpot/$1.git" || git clone "git@git.hubteam.com:HubSpotProtected/$1.git" || echo "🚨 uh oh, something went wrong cloning $1" && exit $EXITCODE
-  fi
-  if [ -d "$CODE_DIR/$1" ]; then
-    cd $CODE_DIR/$1
-  fi
-}
-
-
-# Pulls latest changes from remote if there are any
-# does nothing if branch is dirty
-update_repo() {
-  local branch=$(git_current_branch)
-  # if the branch is dirty, don't update
-  if [[ $(git diff --stat) != '' ]]; then
-    echo "⚠️ $(pwd) is dirty, skipping..."
-  else
-    git checkout master &> /dev/null
-    git pull &> /dev/null
-    git checkout "$branch" &>/dev/null
-    echo "✅ Updated $(pwd)"
-  fi
-}
-
-# Update all repos in $CODE_DIR
-update_repos() {
-  local original_dir=$(pwd)
-  for dir in $CODE_DIR/*; do
-    [[ -d "$dir" ]] || continue
-    {
-      cd "$dir" && is_inside_git_repo && update_repo
-    }
-  done
-  cd "$original_dir"
-}
 
 # tail the asset bender log file
 tail_bend_logs() {
@@ -465,4 +295,35 @@ flexo() {
 
     #--UNSUPPORTED_LOCAL_DEV_SETTING bend-webpack.useWebpack5
     #--UNSUPPORTED_LOCAL_DEV_SETTING bend-webpack.enableFastRefresh\
+}
+
+update_maven_cache() {
+  local current_dir=$(pwd)
+  local NUM_PROC=$(python3  -c 'import multiprocessing; print(multiprocessing.cpu_count())')
+
+  if [[ -z $1 ]]; then
+    cd $CODE_DIR
+    find . -maxdepth 2 -type d -name '.git' | xargs -n 1 stat -f "%m %N" | sort -nr | awk '{print $2}' | xargs -n1 dirname | xargs -P$NUM_PROC -n1 $0
+    #find . -maxdepth 2 -type d -name '.git' -printf "%T@ %p\n" | sort -nr | awk '{print $2}' | xargs -n1 dirname | xargs -P$NUM_PROC -n1 $0
+    #find . -maxdepth 1 -type d -print0 | xargs -P$NUM_PROC -n1 -0 $0
+    rm -f /tmp/*.mvn.log
+    cd "$current_dir"
+    exit 0
+  fi
+
+  echo "Pulling deps for $1"
+
+  cd "$1"
+
+  if [[ -e ".git" ]]; then
+    if [[ -e "pom.xml" ]]; then
+      mvn -U dependency:go-offline &> /tmp/$$.mvn.log
+      if [[ $? -ne 0 ]]; then
+        echo "Failed "$(basename $(pwd))
+      else
+        echo "Done with "$(basename $(pwd))
+      fi
+    fi
+  fi
+  cd "$current_dir"
 }
